added genznodes endpoints for mars-1
cosmos/chain-registry pull request #1347
Opened 2023-02-03 06:45 UTC by Genz22

- rest
- grpc
- rpc

2023-02-03 16:36 UTC, dylanschultzie requested changes

2023-02-04 02:19 UTC, Genz22 commented
@dylanschultzie sorry for the lack of focus

2023-02-06 18:46 UTC, JeremyParish69 approved these changes
LGTM

2023-02-19 17:06 UTC, dylanschultzie approved these changes

2023-02-19 17:07 UTC, merged