Update chain.json
cosmos/chain-registry pull request #1507
Opened 2023-02-25 17:43 UTC by nodeiistt

2023-02-26 21:43 UTC, JeremyParish69 commented on arkh/chain.json
> +        "provider": "arkhnetwork"
Should the providers be 'Nodeist'?

2023-02-27 15:24 UTC, dylanschultzie requested changes

2023-02-27 15:24 UTC, dylanschultzie commented on arkh/chain.json
> +        "provider": "arkhnetwork"
⬆️

2023-02-27 15:24 UTC, dylanschultzie commented
@nodeiistt please provide better PR names in the future

2023-03-01 09:26 UTC, closed without merging

2023-03-01 09:26 UTC, nodeiistt commented on arkh/chain.json
> +        "provider": "arkhnetwork"
I'm opening a new pr thanks.