docs: Update comoshub for v10.0.0 release
cosmos/chain-registry pull request #2250
Opened 2023-06-01 16:58 UTC by mmulji-ic

### Not to be merged until CosmosHub block height 15213800 has passed

2023-06-02 21:50 UTC, dylanschultzie requested changes

2023-06-02 21:50 UTC, dylanschultzie commented on cosmoshub/chain.json
> +        "name": "v10-Epsilon",
Please create a new section here, not override v9

2023-06-02 21:50 UTC, dylanschultzie commented on cosmoshub/chain.json
> +        "name": "v10-Epsilon",
Version should be `v10`: https://www.mintscan.io/cosmos/proposals/798

2023-06-02 21:50 UTC, dylanschultzie commented on cosmoshub/chain.json
>          "height": 15213800,
Make sure to set the appropriate height and "proposal": 798

2023-06-02 21:51 UTC, dylanschultzie commented
est time: `Wed Jun 21 2023 20:48:27Z`

2023-06-21 18:36 UTC, MSalopek approved these changes

2023-06-21 18:37 UTC, MSalopek commented on cosmoshub/chain.json
>          "name": "v9-Lambda",
Is this correct?

2023-06-21 18:38 UTC, MSalopek commented on cosmoshub/chain.json
>          "name": "v9-Lambda",
Yes it is. It is correct :D

2023-06-21 18:39 UTC, yaruwangway approved these changes

2023-06-21 19:02 UTC, dylanschultzie approved these changes

2023-06-21 19:04 UTC, merged