Update chain.json
cosmos/chain-registry pull request #2497
Opened 2023-07-10 12:49 UTC by BccNodes

2023-07-10 18:57 UTC, JeremyParish69 commented on nois/chain.json
> +      "url": "https://explorer.bccnodes.com/nois-M",
Explorer doesn't seem to show any data?

2023-07-14 17:05 UTC, dylanschultzie commented
@BccNodes please provide an appropriate PR title

2023-07-20 15:41 UTC, dylanschultzie requested changes
Please update PR title

2023-08-09 02:09 UTC, JeremyParish69 commented
inactive PR

2023-08-09 02:09 UTC, closed without merging