Add OnFinality RPC Endpoint for Kava to chain.json
cosmos/chain-registry pull request #2512
Opened 2023-07-12 13:55 UTC by deverka

2023-07-12 14:02 UTC, ankurdotb requested changes
The structure is fine, but if I hit https://kava.api.onfinality.io/public/status I get the following error message:

`{"jsonrpc":"2.0","id":"0","error":{"code":-32603,"message":"error processing the request: Error parsing relay: Error unmarshalling relay as json"}}`

Is this RPC endpoint functional?

2023-07-12 14:07 UTC, deverka commented
Yes, it is functional. Let me cross check with the team

2023-07-13 03:54 UTC, hugh-onf commented
@ankurdotb this endpoint only supports EVM RPC
`curl -X POST https://kava.api.onfinality.io/public -d '{"id": 1,"jsonrpc": "2.0","method": "eth_blockNumber"}' -H 'Content-Type: application/json'`

![image](https://github.com/cosmos/chain-registry/assets/105209853/f1011672-40ec-4ff1-adf1-2da6ce720aab)
Would it be an issue?

Thanks.

2023-07-14 17:04 UTC, dylanschultzie requested changes

2023-07-14 17:04 UTC, dylanschultzie commented on kava/chain.json
> +        "address": "https://kava.api.onfinality.io/public",
I believe this should be moved to line 171 under `evm`

2023-09-06 23:36 UTC, deverka commented
PR udpated! Sorry for a late response.

2023-09-20 22:21 UTC, merged