Add AssetMantle
cosmos/chain-registry pull request #285
Opened 2022-04-18 18:20 UTC by tombeynon

Genesis and peers are from: https://github.com/AssetMantle/genesisTransactions/tree/main/mantle-1. Not sure if we want to list all peers?

The logo image is a Github avatar right now, but I can inline it in this repo if that's preferred. 

Rushed together for restake.app but happy to make any changes needed.

2022-04-21 11:42 UTC, Galadrin requested changes

2022-04-21 11:42 UTC, Galadrin commented on assetmantle/assetlist.json
> +        "name": "Mantle",
```suggestion
        "name": "AssetMantle",
```

2022-04-21 11:51 UTC, Galadrin commented on assetmantle/chain.json
> +                "address": "https://rpc-assetmantle.ecostake.com",
```
{
    "address": "https://rpc.assetmantle.one/",
    "provider": "AssetMantle"
}
```

2022-04-21 11:51 UTC, Galadrin commented on assetmantle/chain.json
> +                "address": "https://rest-assetmantle.ecostake.com",
```
{
    "address": "https://rest.assetmantle.one/",
    "provider": "AssetMantle"
}
```

2022-04-21 11:51 UTC, Galadrin commented on assetmantle/chain.json
> +            "tx_page": "https://explorer.postcapitalist.io/AssetMantle/tx/${txHash}"
```
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/asset-mantle",
            "tx_page": "https://www.mintscan.io/asset-mantle/txs/${txHash}"
        },
        {
            "kind": "other",
            "url": "https://explorer.assetmantle.one",
            "tx_page": "https://explorer.assetmantle.one/transactions/${txHash}"
        }
            
```

2022-04-22 09:31 UTC, Sdpierret approved these changes

2022-04-22 09:32 UTC, Galadrin approved these changes

2022-04-22 19:55 UTC, sunnya97 commented on assetmantle/assetlist.json
> +          "png": "https://avatars.githubusercontent.com/u/97742402?s=200&v=4"
Could we pull this into this repo.  (make a subfolder called images inside the assetmantle folder)

2022-04-22 19:55 UTC, sunnya97 commented on assetmantle/assetlist.json
> +          "png": "https://avatars.githubusercontent.com/u/97742402?s=200&v=4"
Going to merge for now, please do this in a new PR

2022-04-22 19:55 UTC, merged