Add OMSO
cosmos/chain-registry pull request #3889
Opened 2024-02-16 10:32 UTC by emileadipura

2024-02-16 20:00 UTC, emileadipura commented
Check @JeremyParish69

2024-02-17 21:05 UTC, JeremyParish69 commented on neutron/assetlist.json
> +      "description": "Astro BOY",
This has already been added a few lines up. Please remove this duplicate.

2024-02-17 21:05 UTC, JeremyParish69 commented on osmosis/assetlist.json
> +      "description": "Created as a culmination of all the memeable events on osmosis.",
Please don't overwrite previously added assets.

2024-02-19 18:55 UTC, JeremyParish69 requested changes
Please don't change anything else in the file. Don't remove the original BOY and don't delete BADKID.

2024-02-20 02:06 UTC, closed without merging