WIP: Update chain.json for IRISnet
cosmos/chain-registry pull request #54
Opened 2021-11-11 12:13 UTC by zhangyelong

2021-11-12 18:01 UTC, sunnya97 commented on irisnet/chain.json
> +    "binaries": {}
```suggestion
```

2021-11-12 18:03 UTC, sunnya97 requested changes

2021-11-12 18:03 UTC, sunnya97 commented on irisnet/chain.json
> +      "a17d7923293203c64ba75723db4d5f28e642f469@seed-2.mainnet.irisnet.org:26656"
Hi, could you please put these in the format used in the chain.json

Example:
```

            {
                "id": "cfb6f2d686014135d4a6034aa6645abd0020cac6",
                "address": "52.79.88.57:26656",
                "provider": "cosmostation"
            }
```

2021-11-12 18:03 UTC, sunnya97 commented on irisnet/chain.json
> +    "https://irishub.iobscan.io",
Same with these.  Please use the format in the example (check the Osmosis chain.json for an example)

2022-01-12 15:28 UTC, jackzampolin commented
Closing this as stale, also it looks like the registry has been since updated.

2022-01-12 15:28 UTC, closed without merging